FROM mcr.microsoft.com/dotnet/sdk:8.0 AS builder
WORKDIR /src

COPY IssueGPT.Api/IssueGPT.Api.csproj ./IssueGPT.Api/
RUN dotnet restore ./IssueGPT.Api/IssueGPT.Api.csproj

COPY IssueGPT.Api/ ./IssueGPT.Api/
WORKDIR /src/IssueGPT.Api
RUN dotnet build -c Release -o /app/build

FROM builder AS publish
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000

ENTRYPOINT ["dotnet", "IssueGPT.Api.dll"]
