apiVersion: v1
kind: Secret
metadata:
  name: issuegpt-secrets
  namespace: issuegpt
type: Opaque
stringData:
  DB_PASSWORD: "IssueGPT@2026"
  GITHUB_TOKEN: "ghp_YOUR_GITHUB_TOKEN_HERE"
  OPENAI_API_KEY: "sk-YOUR_OPENAI_KEY_HERE"
